import { prisma } from '@/lib/prisma';
import Link from 'next/link';
import { Suspense } from 'react';
import DeleteButton from '@/components/DeleteButton';

export const dynamic = 'force-dynamic';

function StatusFilter({ current }: { current: string }) {
  const filters = [
    { key: '', label: '全部' },
    { key: 'PUBLISHED', label: '已发布' },
    { key: 'DRAFT', label: '草稿' },
    { key: 'ARCHIVED', label: '已归档' },
  ];
  return (
    <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
      {filters.map(f => (
        <Link key={f.key} href={f.key ? `/admin/posts?status=${f.key}` : '/admin/posts'}
          style={{ padding: '6px 14px', borderRadius: 8, fontSize: '.85rem', fontWeight: 600, textDecoration: 'none',
            background: current === f.key ? '#1E3A8A' : '#F3F4F6', color: current === f.key ? '#fff' : '#374151' }}>
          {f.label}
        </Link>
      ))}
    </div>
  );
}

async function PostsTable({ posts }: { posts: Array<any> }) {
  return (
    <div style={{ background: '#fff', borderRadius: 12, overflow: 'hidden', boxShadow: '0 2px 8px rgba(0,0,0,0.04)' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead>
          <tr style={{ background: '#F9FAFB', borderBottom: '1px solid #E5E7EB' }}>
            <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '.85rem', fontWeight: 600, color: '#6B7280' }}>标题</th>
            <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '.85rem', fontWeight: 600, color: '#6B7280' }}>分类</th>
            <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '.85rem', fontWeight: 600, color: '#6B7280' }}>状态</th>
            <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '.85rem', fontWeight: 600, color: '#6B7280' }}>来源</th>
            <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '.85rem', fontWeight: 600, color: '#6B7280' }}>浏览</th>
            <th style={{ padding: '12px 16px', textAlign: 'left', fontSize: '.85rem', fontWeight: 600, color: '#6B7280' }}>日期</th>
            <th style={{ padding: '12px 16px', textAlign: 'right', fontSize: '.85rem', fontWeight: 600, color: '#6B7280' }}>操作</th>
          </tr>
        </thead>
        <tbody>
          {posts.map(post => (
            <tr key={post.id} style={{ borderBottom: '1px solid #F3F4F6' }}>
              <td style={{ padding: '12px 16px', fontSize: '.9rem', maxWidth: 300, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{post.title}</td>
              <td style={{ padding: '12px 16px', fontSize: '.85rem' }}>{post.category.name}</td>
              <td style={{ padding: '12px 16px' }}>
                <span style={{ fontSize: '.78rem', padding: '2px 8px', borderRadius: 4, background: post.status === 'PUBLISHED' ? '#D1FAE5' : post.status === 'DRAFT' ? '#FEF3C7' : '#F3F4F6', color: post.status === 'PUBLISHED' ? '#065F46' : post.status === 'DRAFT' ? '#92400E' : '#6B7280' }}>{post.status === 'PUBLISHED' ? '已发布' : post.status === 'DRAFT' ? '草稿' : '已归档'}</span>
              </td>
              <td style={{ padding: '12px 16px', fontSize: '.82rem', color: '#9CA3AF' }}>
                {post.autoGenerated && <span style={{ background: '#DBEAFE', color: '#1E3A8A', padding: '2px 6px', borderRadius: 4, fontSize: '.75rem', marginRight: 6 }}>自动生成</span>}
                {post.sourceName && <span>{post.sourceName}</span>}
              </td>
              <td style={{ padding: '12px 16px', fontSize: '.85rem', color: '#6B7280' }}>{post.views}</td>
              <td style={{ padding: '12px 16px', fontSize: '.8rem', color: '#9CA3AF' }}>{new Date(post.createdAt).toISOString().slice(0, 10)}</td>
              <td style={{ padding: '12px 16px', textAlign: 'right' }}>
                <Link href={`/admin/posts/${post.id}`} style={{ color: '#1E3A8A', fontSize: '.82rem', fontWeight: 600, marginRight: 12, textDecoration: 'none' }}>编辑</Link>
                {post.status === 'DRAFT' && (
                  <form action={`/api/admin/posts/${post.id}/publish`} method="POST" style={{ display: 'inline' }}>
                    <button type="submit" style={{ background: 'none', border: 'none', color: '#059669', fontSize: '.82rem', fontWeight: 600, cursor: 'pointer' }}>发布</button>
                  </form>
                )}
                <DeleteButton id={post.id} />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default async function AdminPosts({ searchParams }: { searchParams?: { status?: string } }) {
  const status = searchParams?.status;
  const where = status ? { status } : {};
  const posts = await prisma.post.findMany({
    where,
    include: { category: true },
    orderBy: { createdAt: 'desc' },
  });

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <h1 style={{ fontSize: '1.5rem', fontWeight: 800 }}>文章管理</h1>
        <Link href="/admin/posts/new" style={{ background: '#1E3A8A', color: '#fff', padding: '8px 20px', borderRadius: 8, fontSize: '.9rem', fontWeight: 600, textDecoration: 'none' }}>✏️ 发布文章</Link>
      </div>
      <StatusFilter current={status || ''} />
      <Suspense fallback={<div style={{ padding: 32, color: '#9CA3AF' }}>加载中...</div>}>
        <PostsTable posts={posts} />
      </Suspense>
    </div>
  );
}
