import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import bcrypt from 'bcryptjs';
import { getQAItems } from '@/lib/qaSeedData';

export const dynamic = 'force-dynamic';

export async function GET() {
  const logs: string[] = [];

  try {
    // 1. Create Additive table
    logs.push('Creating Additive table...');
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS "Additive" (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL,
        alias TEXT NOT NULL DEFAULT '',
        "casNumber" TEXT,
        "functionClass" TEXT NOT NULL,
        "maxLimit" TEXT NOT NULL,
        "foodCategory" TEXT NOT NULL,
        remarks TEXT NOT NULL DEFAULT '',
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);
    logs.push('Additive table OK');

    // 2. Create TroubleshootNode table
    logs.push('Creating TroubleshootNode table...');
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS "TroubleshootNode" (
        id SERIAL PRIMARY KEY,
        category TEXT NOT NULL,
        question TEXT NOT NULL,
        options TEXT NOT NULL,
        "isLeaf" BOOLEAN NOT NULL DEFAULT false,
        advice TEXT,
        "parentId" INTEGER,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);
    logs.push('TroubleshootNode table OK');

    // 3. Add missing columns to PilotLine
    logs.push('Adding PilotLine.capacity...');
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "capacity" TEXT NOT NULL DEFAULT ''`);
      logs.push('PilotLine.capacity OK');
    } catch (e) {
      logs.push('PilotLine.capacity already exists or skip');
    }

    // 4. Add missing columns to User
    logs.push('Adding User.phone/company/lastLogin...');
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "company" TEXT`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastLogin" TIMESTAMP(3)`);
      logs.push('User columns OK');
    } catch (e) {
      logs.push('User columns already exist or skip');
    }

    // 5. Add missing columns to Booking
    logs.push('Adding Booking columns...');
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "contactEmail" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "experimentType" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "preferredDate" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PENDING'`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "adminNote" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3)`);
      // Update updatedAt for existing records
      await prisma.$executeRawUnsafe(`UPDATE "Booking" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL`);
      logs.push('Booking columns OK');
    } catch (e) {
      logs.push('Booking columns already exist or skip');
    }

    // 6. Create Setting table
    logs.push('Creating Setting table...');
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS "Setting" (
        id SERIAL PRIMARY KEY,
        key TEXT NOT NULL UNIQUE,
        value TEXT NOT NULL
      )
    `);
    logs.push('Setting table OK');

    // 6.5 Add Post new columns (sourceUrl, sourceName, autoGenerated, updatedAt)
    logs.push('Adding Post new columns...');
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "sourceUrl" TEXT`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "sourceName" TEXT`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3)`);
      // Update updatedAt for existing records
      await prisma.$executeRawUnsafe(`UPDATE "Post" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL`);
      logs.push('Post new columns OK');
    } catch (e) {
      logs.push('Post columns already exist or skip');
    }

    // 6.7 Seed default notification settings
    logs.push('Seeding notification settings...');
    const defaultSettings = [
      { key: 'notify_email', value: 'gwei10@qq.com' },
      { key: 'notify_phone', value: '+8618688889823' },
      { key: 'smtp_host', value: '' },
      { key: 'smtp_port', value: '587' },
      { key: 'smtp_user', value: '' },
      { key: 'smtp_pass', value: '' },
      { key: 'smtp_from', value: 'noreply@meattech.pro' },
      { key: 'sms_webhook', value: '' },
      { key: 'article_sources', value: JSON.stringify([
        { name: '食品伙伴网', url: 'https://www.foodmate.net/rss.xml', type: 'rss', category: '中式酱卤肉制品' },
        { name: 'Food Navigator', url: 'https://www.foodnavigator.com/RSS', type: 'rss', category: '西式低温熏煮肉制品' },
        { name: 'Meat Science Journal', url: 'https://www.sciencedirect.com/journal/meat-science/rss', type: 'rss', category: '发酵与肉干制品' },
        { name: '中国肉类协会', url: 'http://www.chinameat.com.cn/', type: 'html', category: '中式酱卤肉制品' },
        { name: '肉制品技术网', url: 'http://www.rouzhipin.com/', type: 'html', category: '速冻调制肉制品（预制菜）' },
      ]) },
      // 邮件通知模板
      { key: 'email_template_confirmed', value: `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;border:1px solid #e5e7eb;border-radius:12px;">
  <h2 style="color:#059669;margin:0 0 16px;">✅ 预约已确认</h2>
  <p style="font-size:1.1rem;margin-bottom:16px;">尊敬的 {{contactName}}，您的预约已<strong>确认</strong></p>
  <table style="width:100%;border-collapse:collapse;">
    <tr><td style="padding:8px 0;color:#6B7280;width:100px;">预约编号</td><td style="padding:8px 0;font-weight:600;">#{{bookingId}}</td></tr>
    <tr><td style="padding:8px 0;color:#6B7280;">预约产线</td><td style="padding:8px 0;">{{lineName}}</td></tr>
    <tr><td style="padding:8px 0;color:#6B7280;">实验需求</td><td style="padding:8px 0;">{{requirement}}</td></tr>
    {{adminNote}}
  </table>
  <div style="margin-top:20px;padding:16px;background:#F9FAFB;border-radius:8px;">
    <div style="font-size:.85rem;color:#6B7280;margin-bottom:8px;">如有疑问，请联系：</div>
    <div style="font-size:.9rem;">📞 电话：400-xxx-xxxx</div>
    <div style="font-size:.9rem;">📧 邮箱：admin@meattech.pro</div>
  </div>
</div>` },
      { key: 'email_template_cancelled', value: `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;border:1px solid #e5e7eb;border-radius:12px;">
  <h2 style="color:#DC2626;margin:0 0 16px;">❌ 预约已取消</h2>
  <p style="font-size:1.1rem;margin-bottom:16px;">尊敬的 {{contactName}}，抱歉您的预约已<strong>取消</strong></p>
  <table style="width:100%;border-collapse:collapse;">
    <tr><td style="padding:8px 0;color:#6B7280;width:100px;">预约编号</td><td style="padding:8px 0;font-weight:600;">#{{bookingId}}</td></tr>
    <tr><td style="padding:8px 0;color:#6B7280;">预约产线</td><td style="padding:8px 0;">{{lineName}}</td></tr>
    {{adminNote}}
  </table>
  <div style="margin-top:20px;padding:16px;background:#F9FAFB;border-radius:8px;">
    <div style="font-size:.85rem;color:#6B7280;margin-bottom:8px;">如有疑问，请联系：</div>
    <div style="font-size:.9rem;">📞 电话：400-xxx-xxxx</div>
    <div style="font-size:.9rem;">📧 邮箱：admin@meattech.pro</div>
  </div>
</div>` },
      { key: 'email_template_in_progress', value: `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;border:1px solid #e5e7eb;border-radius:12px;">
  <h2 style="color:#1E3A8A;margin:0 0 16px;">▶️ 实验执行中</h2>
  <p style="font-size:1.1rem;margin-bottom:16px;">尊敬的 {{contactName}}，您的预约实验已<strong>开始执行</strong></p>
  <table style="width:100%;border-collapse:collapse;">
    <tr><td style="padding:8px 0;color:#6B7280;width:100px;">预约编号</td><td style="padding:8px 0;font-weight:600;">#{{bookingId}}</td></tr>
    <tr><td style="padding:8px 0;color:#6B7280;">预约产线</td><td style="padding:8px 0;">{{lineName}}</td></tr>
  </table>
  <p style="margin-top:16px;color:#6B7280;">我们会在实验完成后第一时间通知您。</p>
</div>` },
      { key: 'email_template_completed', value: `<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;border:1px solid #e5e7eb;border-radius:12px;">
  <h2 style="color:#059669;margin:0 0 16px;">✅ 实验已完成</h2>
  <p style="font-size:1.1rem;margin-bottom:16px;">尊敬的 {{contactName}}，您的预约实验已<strong>完成</strong></p>
  <table style="width:100%;border-collapse:collapse;">
    <tr><td style="padding:8px 0;color:#6B7280;width:100px;">预约编号</td><td style="padding:8px 0;font-weight:600;">#{{bookingId}}</td></tr>
    <tr><td style="padding:8px 0;color:#6B7280;">预约产线</td><td style="padding:8px 0;">{{lineName}}</td></tr>
    {{adminNote}}
  </table>
  <p style="margin-top:16px;">感谢您使用 MeatTech Pro 智能中试平台！</p>
</div>` },
      // 短信通知模板
      { key: 'sms_template_confirmed', value: '【MeatTech Pro】尊敬的{{contactName}}，您的预约 #{{bookingId}} 已确认。预约产线：{{lineName}}。如有疑问请联系 400-xxx-xxxx' },
      { key: 'sms_template_cancelled', value: '【MeatTech Pro】尊敬的{{contactName}}，抱歉您的预约 #{{bookingId}} 已取消。{{adminNote}}如有疑问请联系 400-xxx-xxxx' },
      { key: 'sms_template_in_progress', value: '【MeatTech Pro】尊敬的{{contactName}}，您的预约 #{{bookingId}} 实验已开始执行，我们会及时通知您进度。' },
      { key: 'sms_template_completed', value: '【MeatTech Pro】尊敬的{{contactName}}，您的预约 #{{bookingId}} 实验已完成。{{adminNote}}感谢使用！' },
    ];
    for (const s of defaultSettings) {
      await prisma.$executeRawUnsafe(
        `INSERT INTO "Setting" (key, value) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING`,
        s.key, s.value
      );
    }
    logs.push('Notification settings OK');

    // 7. Seed admin user
    logs.push('Seeding admin user...');
    const existingAdmin = await prisma.user.findUnique({ where: { email: 'admin@meattech.pro' } });
    if (!existingAdmin) {
      await prisma.user.create({
        data: {
          email: 'admin@meattech.pro',
          password: bcrypt.hashSync('admin123', 10),
          name: '平台管理员',
          role: 'ADMIN',
        },
      });
      logs.push('Admin user created');
    } else {
      logs.push('Admin user already exists');
    }

    // 8. Seed categories (upsert to update existing + add new ones)
    logs.push('Seeding categories...');
    const categories = [
      { name: '中式酱卤肉制品', slug: 'chinese-braised', icon: '🍖', order: 1 },
      { name: '西式低温熏煮肉制品', slug: 'western-smoked', icon: '🥓', order: 2 },
      { name: '速冻调制肉制品（预制菜）', slug: 'frozen-prepared', icon: '🥟', order: 3 },
      { name: '发酵与肉干制品', slug: 'fermented-dried', icon: '🧀', order: 4 },
      { name: '工艺问题', slug: 'process-issues', icon: '🔧', order: 5 },
      { name: '产品制作', slug: 'product-making', icon: '🍳', order: 6 },
      { name: '工艺问答', slug: 'community-qa', icon: '💬', order: 7 },
    ];
    for (const cat of categories) {
      await prisma.category.upsert({
        where: { slug: cat.slug },
        create: cat,
        update: { name: cat.name, icon: cat.icon, order: cat.order },
      });
    }
    logs.push(`Categories OK (${categories.length} categories)`);

    // 9. Seed additives
    logs.push('Seeding additives...');
    const additiveCount = await prisma.additive.count();
    if (additiveCount === 0) {
      const additives = [
        { name: '亚硝酸钠', alias: '亚硝酸盐', casNumber: '7632-00-0', functionClass: '护色剂', maxLimit: '0.15 g/kg', foodCategory: '腌制肉制品类、酱卤肉制品类', remarks: '以亚硝酸钠计，残留量≤30mg/kg' },
        { name: '脱氢乙酸钠', alias: '脱氢醋酸钠', casNumber: '4418-26-2', functionClass: '防腐剂', maxLimit: '0.3 g/kg', foodCategory: '发酵肉制品类、预制肉制品类', remarks: '以脱氢乙酸计' },
        { name: 'D-异抗坏血酸钠', alias: '异VC钠', casNumber: '6381-77-7', functionClass: '抗氧化剂', maxLimit: '1.0 g/kg', foodCategory: '预制肉制品、腌制肉制品', remarks: '以抗坏血酸计' },
        { name: '乳酸钠', alias: '', casNumber: '72-17-3', functionClass: '水分保持剂', maxLimit: '按生产需要适量使用', foodCategory: '生湿面制品、肉制品', remarks: 'GMP原则，无具体限量' },
        { name: '山梨酸钾', alias: '山梨酸盐', casNumber: '24634-61-5', functionClass: '防腐剂', maxLimit: '0.075 g/kg', foodCategory: '肉灌肠类', remarks: '以山梨酸计' },
        { name: '红曲红', alias: '红曲色素', casNumber: null, functionClass: '着色剂', maxLimit: '按生产需要适量使用', foodCategory: '熟肉制品、腌制肉制品', remarks: '天然色素，GMP原则' },
        { name: '卡拉胶', alias: '鹿角藻胶', casNumber: '9000-07-1', functionClass: '增稠剂', maxLimit: '按生产需要适量使用', foodCategory: '肉制品', remarks: '需标注' },
        { name: '海藻酸钠', alias: '褐藻酸钠', casNumber: '9005-38-3', functionClass: '增稠剂', maxLimit: '按生产需要适量使用', foodCategory: '肉制品', remarks: '常与卡拉胶复配使用' },
        { name: '乳酸链球菌素', alias: 'Nisin', casNumber: '1414-45-5', functionClass: '防腐剂', maxLimit: '0.5 g/kg', foodCategory: '肉制品', remarks: '生物防腐剂，天然发酵产物' },
        { name: '谷氨酰胺转氨酶', alias: 'TG酶', casNumber: '80146-85-6', functionClass: '稳定剂和凝固剂', maxLimit: '按生产需要适量使用', foodCategory: '肉制品', remarks: '可改善肉质结构' },
      ];
      for (const a of additives) {
        await prisma.additive.create({ data: a });
      }
      logs.push(`Seeded ${additives.length} additives`);
    } else {
      logs.push(`Additives already seeded (${additiveCount})`);
    }

    // 10. Seed troubleshoot nodes
    logs.push('Seeding troubleshoot nodes...');
    const nodeCount = await prisma.troubleshootNode.count();
    if (nodeCount === 0) {
      const nodes = [
        { category: '出水/汁液流失', question: '产品出水发生在哪个环节？', options: JSON.stringify([{ text: '蒸煮后冷却阶段出水', nextNodeId: 2 }, { text: '切片/包装时出水', nextNodeId: 3 }, { text: '储存/货架期出水', nextNodeId: 4 }]), isLeaf: false },
        { category: '出水/汁液流失', question: '蒸煮后冷却阶段出水，检查蒸煮中心温度是否达标？', options: JSON.stringify([{ text: '中心温度未达到72℃', nextNodeId: 5 }, { text: '中心温度已达标(≥72℃)', nextNodeId: 6 }]), isLeaf: false },
        { category: '出水/汁液流失', question: '切片出水通常与降温速率有关，核心降温速率是否≤4℃/h？', options: JSON.stringify([{ text: '降温速率过慢', nextNodeId: 7 }, { text: '降温速率正常', nextNodeId: 6 }]), isLeaf: false },
        { category: '出水/汁液流失', question: '货架期出水可能与包装阻隔性有关，是否使用高阻隔包装膜？', options: JSON.stringify([{ text: '是，使用高阻隔膜', nextNodeId: 6 }, { text: '否，普通包装膜', nextNodeId: 8 }]), isLeaf: false },
        { category: '出水/汁液流失', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：蒸煮F值不足</strong><br/>中心温度未达到72℃导致蛋白质变性不充分，持水网络未完全形成。<br/><strong>建议：</strong><br/>1. 提高蒸煮温度或延长蒸煮时间，确保中心温度≥72℃<br/>2. 检查蒸煮炉温度均匀性<br/>3. 校准中心温度探针精度' },
        { category: '出水/汁液流失', question: '检查滚揉工艺参数', options: JSON.stringify([{ text: '滚揉真空度≥-0.08MPa', nextNodeId: 9 }, { text: '滚揉真空度不足', nextNodeId: 10 }]), isLeaf: false },
        { category: '出水/汁液流失', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：降温速率不足</strong><br/>核心降温速率过慢导致冰晶粗大，破坏蛋白质凝胶结构。<br/><strong>建议：</strong><br/>1. 增加冷却水流量或降低水温<br/>2. 缩短产品从蒸煮到冷却的转移时间<br/>3. 考虑使用液氮速冻替代常规冷却' },
        { category: '出水/汁液流失', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：包装阻隔性不足</strong><br/>普通包装膜透水率高，导致货架期水分蒸发冷凝。<br/><strong>建议：</strong><br/>1. 更换7层共挤高阻隔膜(EVOH)<br/>2. 采用气调包装(70%N₂+30%CO₂)<br/>3. 检查封口完整性' },
        { category: '出水/汁液流失', question: '检查盐水注射率', options: JSON.stringify([{ text: '注射率≤20%', nextNodeId: 6 }, { text: '注射率>20%', nextNodeId: 11 }]), isLeaf: false },
        { category: '出水/汁液流失', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：滚揉真空度不足</strong><br/>真空度不够导致肌原纤维蛋白提取不充分，持水性下降。<br/><strong>建议：</strong><br/>1. 检查真空泵性能，确保真空度≥-0.08MPa<br/>2. 检查滚揉筒密封圈<br/>3. 适当延长滚揉时间（总时间≥4h）' },
        { category: '出水/汁液流失', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：盐水注射率过高</strong><br/>注射率超过20%时，蛋白质网络无法有效束缚多余水分。<br/><strong>建议：</strong><br/>1. 将注射率控制在15-20%<br/>2. 添加0.3%复配磷酸盐提升持水<br/>3. 考虑使用滚揉替代部分注射' },
        { category: '出油/脂肪游离', question: '出油发生在哪个阶段？', options: JSON.stringify([{ text: '蒸煮过程中出油', nextNodeId: 13 }, { text: '成品切片时出油', nextNodeId: 14 }]), isLeaf: false },
        { category: '出油/脂肪游离', question: '蒸煮升温速率是否过快？', options: JSON.stringify([{ text: '升温速率>3℃/min', nextNodeId: 15 }, { text: '升温速率正常', nextNodeId: 16 }]), isLeaf: false },
        { category: '出油/脂肪游离', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：降温过程中脂肪结晶粗大</strong><br/>切片时脂肪融化溢出。<br/><strong>建议：</strong><br/>1. 提高降温速率，快速通过脂肪结晶温度带<br/>2. 切片前确保产品中心温度≤4℃<br/>3. 检查脂肪原料新鲜度' },
        { category: '出油/脂肪游离', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：蒸煮升温过快</strong><br/>升温速率过快导致脂肪细胞破裂，油脂游离。<br/><strong>建议：</strong><br/>1. 采用阶梯式升温：55℃→65℃→75℃<br/>2. 每段升温速率≤2℃/min<br/>3. 增加中间持温段' },
        { category: '出油/脂肪游离', question: '脂肪原料是否预处理？', options: JSON.stringify([{ text: '未预处理', nextNodeId: 17 }, { text: '已预处理', nextNodeId: 18 }]), isLeaf: false },
        { category: '出油/脂肪游离', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：脂肪未预冷处理</strong><br/>脂肪直接使用导致斩拌中温度升高过快。<br/><strong>建议：</strong><br/>1. 脂肪预冷至-4~-2℃后再投入斩拌<br/>2. 斩拌过程中加冰屑控温<br/>3. 斩拌终温控制在≤8℃' },
        { category: '出油/脂肪游离', question: '', options: '[]', isLeaf: true, advice: '<strong>排查完成：基础工艺正常</strong><br/>建议检查：<br/>1. 脂肪与瘦肉比例是否合理（建议≤30%）<br/>2. 乳化剂添加量是否足够<br/>3. 灌装压力是否过大' },
        { category: '切片散碎', question: '切片散碎的方向是？', options: JSON.stringify([{ text: '纵向断裂（沿纤维方向）', nextNodeId: 20 }, { text: '横向断裂（垂直纤维方向）', nextNodeId: 21 }]), isLeaf: false },
        { category: '切片散碎', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：凝胶强度不足</strong><br/>纵向断裂通常因蛋白质凝胶网络不完整。<br/><strong>建议：</strong><br/>1. 检查滚揉是否充分（提取盐溶蛋白）<br/>2. 确保腌制时间≥12h<br/>3. 添加0.2%大豆分离蛋白增强凝胶' },
        { category: '切片散碎', question: '产品冷却是否充分？', options: JSON.stringify([{ text: '中心温度≤4℃', nextNodeId: 22 }, { text: '中心温度>4℃', nextNodeId: 23 }]), isLeaf: false },
        { category: '切片散碎', question: '', options: '[]', isLeaf: true, advice: '<strong>基础工艺正常</strong><br/>建议检查：<br/>1. 切片刀锋利度和转速<br/>2. 切片厚度设置<br/>3. 添加结着剂（如TG酶）改善切片性' },
        { category: '切片散碎', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：冷却不充分</strong><br/>产品中心温度过高时切片，凝胶尚未完全定型。<br/><strong>建议：</strong><br/>1. 确保切片前中心温度≤4℃<br/>2. 延长冷却时间<br/>3. 检查冷库温度是否达标（≤0℃）' },
        { category: '色泽异常', question: '色泽异常的具体表现？', options: JSON.stringify([{ text: '色泽发暗/偏黑', nextNodeId: 25 }, { text: '色泽发白/偏浅', nextNodeId: 26 }, { text: '色泽不均匀', nextNodeId: 27 }]), isLeaf: false },
        { category: '色泽异常', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：亚硝酸盐用量异常或美拉德反应过度</strong><br/><strong>建议：</strong><br/>1. 校验亚硝酸钠添加量（≤0.15g/kg）<br/>2. 检查残留量是否在30mg/kg以内<br/>3. 降低烟熏温度/时间，防止过度美拉德反应<br/>4. 检查原料肉新鲜度' },
        { category: '色泽异常', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：发色不充分或亚硝酸盐不足</strong><br/><strong>建议：</strong><br/>1. 检查亚硝酸钠添加量是否达标<br/>2. 延长发色时间（腌制≥12h）<br/>3. 确保腌制温度2-4℃<br/>4. 添加D-异抗坏血酸钠（0.05%）助发色' },
        { category: '色泽异常', question: '', options: '[]', isLeaf: true, advice: '<strong>原因：原料差异或加工不均匀</strong><br/><strong>建议：</strong><br/>1. 统一原料肉来源和批次<br/>2. 确保滚揉均匀（间歇式滚揉，正反转交替）<br/>3. 检查蒸煮温度均匀性<br/>4. 控制产品直径一致' },
      ];
      for (const n of nodes) {
        await prisma.troubleshootNode.create({ data: n });
      }
      logs.push(`Seeded ${nodes.length} troubleshoot nodes`);
    } else {
      logs.push(`Troubleshoot nodes already seeded (${nodeCount})`);
    }

    // 11. Update PilotLine with capacity if missing (use raw SQL to avoid Prisma schema mismatch)
    logs.push('Updating pilot lines with capacity...');
    try {
      const pilotLines = await prisma.$queryRaw<Array<{ id: number; name: string; capacity: string }>>`SELECT id, name, capacity FROM "PilotLine"`;
      const capacityMap: Record<string, string> = {
        '120L 真空斩拌机': '120kg/批次',
        '连续式全自动烟熏炉': '500kg/h',
        '液氮速冻隧道产线': '2t/h',
      };
      for (const pl of pilotLines) {
        if (!pl.capacity && capacityMap[pl.name]) {
          await prisma.$executeRawUnsafe(`UPDATE "PilotLine" SET capacity = $1 WHERE id = $2`, capacityMap[pl.name], pl.id);
        }
      }
      logs.push('Pilot lines capacity OK');
    } catch (e) {
      logs.push('Pilot lines capacity skip (columns may not exist yet)');
    }

    // 12. Add new columns to PilotLine (equipment, capabilities, contact info, pricing)
    logs.push('Adding new columns to PilotLine...');
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "equipment" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "capabilities" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "contactPerson" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "contactPhone" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "contactEmail" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "pricePerDay" DOUBLE PRECISION NOT NULL DEFAULT 0`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "serviceFeePercent" DOUBLE PRECISION NOT NULL DEFAULT 5`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "images" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'UNIVERSITY'`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "advantages" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "cooperationModel" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "PilotLine" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3)`);
      // Update updatedAt for existing records
      await prisma.$executeRawUnsafe(`UPDATE "PilotLine" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL`);
      logs.push('PilotLine new columns OK');
    } catch (e) {
      logs.push('PilotLine new columns already exist or skip');
    }

    // 12.5 Seed Pearl River Delta (粤港澳大湾区) pilot institutions
    logs.push('Seeding PRD pilot institutions...');
    const prdInstitutions = [
      {
        name: '华南理工大学 食品科学与工程学院',
        region: '华南',
        status: 'AVAILABLE',
        type: 'UNIVERSITY',
        specs: '中试车间：乳化斩拌、真空滚揉、超高压灭菌（HPP）',
        capacity: '200kg/批次',
        equipment: '乳化斩拌机,真空滚揉机,超高压灭菌设备(HPP),灌装机,蒸煮槽',
        capabilities: '肉品现代加工,蛋白质改性,脂质氧化控制,清洁标签,减盐技术',
        advantages: '华南地区食品界的黄埔军校。在肉品现代加工、蛋白质改性、脂质氧化控制方面全国领先。中试车间拥有先进的乳化斩拌、真空滚揉及超高压灭菌（HPP）等设备，非常适合高端肉制品的中试放大。',
        cooperationModel: 'CRO高客单价分成：适合"找专家、做大改动"的高难度中试需求，如清洁标签、减盐、肉品保水机制等硬核改性研发。',
        contactPerson: '科研对接办公室',
        contactPhone: '020-8711xxxx',
        contactEmail: 'food@scut.edu.cn',
        pricePerDay: 8000,
        serviceFeePercent: 10,
        description: '华南理工大学食品科学与工程学院是华南地区食品科学与工程领域的顶尖学府，拥有国家级重点实验室。中试车间配备完整的乳化斩拌、真空滚揉、超高压灭菌（HPP）等先进设备，特别适合高端肉制品的工艺放大与硬核改性研究。',
      },
      {
        name: '华南农业大学 食品学院',
        region: '华南',
        status: 'AVAILABLE',
        type: 'UNIVERSITY',
        specs: '畜禽产品加工中试生产线',
        capacity: '300kg/批次',
        equipment: '畜禽产品加工中试线,真空滚揉机,盐水注射机,烟熏炉,灌装机',
        capabilities: '畜禽产品加工,中式酱卤肉制品,西式低温肉制品,工艺调试',
        advantages: '畜禽产品加工是其传统强项，与温氏股份等肉企巨头有长期深度合作。拥有专门的畜禽产品加工中试生产线，对于中式酱卤肉制品、西式低温肉制品的工艺调试经验极其丰富。',
        cooperationModel: 'CRO高客单价分成：适合需要深度工艺调试的中式酱卤、西式低温肉制品研发项目，可与温氏等产业资源对接。',
        contactPerson: '学院科研办',
        contactPhone: '020-8528xxxx',
        contactEmail: 'food@scau.edu.cn',
        pricePerDay: 6000,
        serviceFeePercent: 10,
        description: '华南农业大学食品学院在畜禽产品加工领域具有传统优势，与温氏股份等龙头企业长期合作。中试生产线覆盖从原料处理到成品包装全流程，对中式酱卤、西式低温肉制品的工艺调试经验丰富。',
      },
      {
        name: '广东省农业科学院 蚕业与农产品加工研究所',
        region: '华南',
        status: 'AVAILABLE',
        type: 'UNIVERSITY',
        specs: '中试基地：预制菜、传统肉制品现代化',
        capacity: '150kg/批次',
        equipment: '广式腊味中试线,盐焗鸡工业化产线,真空包装机,烘干房',
        capabilities: '预制菜,传统肉制品现代化,广式腊味,盐焗鸡工业化,专利转化',
        advantages: '畜禽加工研究团队在预制菜、传统肉制品现代化（如广式腊味、盐焗鸡工业化）领域拥有大量专利。中试基地专门对外提供技术服务，商业化对接流程比高校更为灵活。',
        cooperationModel: 'CRO高客单价分成 + 专利转化：适合传统肉制品工业化升级项目，可对接专利技术转化，流程比高校更灵活。',
        contactPerson: '技术服务中心',
        contactPhone: '020-8723xxxx',
        contactEmail: 'gdaas@vip.163.com',
        pricePerDay: 5000,
        serviceFeePercent: 10,
        description: '广东省农科院蚕业与农产品加工研究所在预制菜和传统肉制品现代化领域拥有大量专利技术，中试基地对外开放提供技术服务，商业化对接流程灵活高效。特别适合广式腊味、盐焗鸡等传统肉制品的工业化升级项目。',
      },
      {
        name: '佛山顺德预制菜产业园 公共中试平台',
        region: '华南',
        status: 'AVAILABLE',
        type: 'PARK',
        specs: '工业级调理肉制品、速冻肉类中试线（含液氮速冻隧道）',
        capacity: '500kg/h',
        equipment: '液氮速冻隧道,真空包装机,调理肉制品中试线,速冻肉类中试线',
        capabilities: '调理肉制品,速冻肉类,预制菜,轻资产研发',
        advantages: '佛山顺德作为"世界美食之都"，近年来大力打造预制菜。公共服务平台配备了工业级的调理肉制品、速冻肉类中试线，重点解决中小微餐饮品牌"无钱建产线、大厂不给代工"的痛点。',
        cooperationModel: '标准场租抽佣：适合初创品牌、预制菜试错需求。政府考核产线闲置率指标，非常欢迎平台带客，收费公开透明。',
        contactPerson: '产业园管委会',
        contactPhone: '0757-2283xxxx',
        contactEmail: 'sdypc@shunde.gov.cn',
        pricePerDay: 3000,
        serviceFeePercent: 8,
        description: '佛山顺德预制菜产业园是"世界美食之都"顺德重点打造的预制菜产业平台。公共中试平台配备工业级调理肉制品、速冻肉类中试线（含液氮速冻隧道、真空包装机等），专为中小微品牌解决"无钱建产线、大厂不给代工"的痛点。收费公开透明，对中小企业非常友好。',
      },
      {
        name: '肇庆（高要）预制菜产业园 公共中试仓',
        region: '华南',
        status: 'AVAILABLE',
        type: 'PARK',
        specs: '全套柔性设备：原料处理→斩拌→灌装→熟制→速冻包装',
        capacity: '400kg/h',
        equipment: '原料处理设备,斩拌机,灌装机,熟制设备,速冻包装线',
        capabilities: '预制菜,柔性中试,中央厨房研发,全流程打样',
        advantages: '建设有专门的"预制菜公共中试仓"，提供从原料处理、斩拌、灌装、熟制到速冻包装的全套柔性设备，旨在打造粤港澳大湾区的"中央厨房研发总部"。',
        cooperationModel: '标准场租抽佣：适合初创品牌的全流程打样需求，政府扶持平台，产线柔性高，可快速切换产品品类。',
        contactPerson: '高要产业园运营办',
        contactPhone: '0758-839xxxx',
        contactEmail: 'gyypc@zhaoqing.gov.cn',
        pricePerDay: 2500,
        serviceFeePercent: 8,
        description: '肇庆（高要）预制菜产业园公共中试仓是粤港澳大湾区"中央厨房研发总部"的核心载体。提供从原料处理、斩拌、灌装、熟制到速冻包装的全套柔性设备，专为预制菜企业提供低成本、高效率的中试打样服务。',
      },
      {
        name: 'IFF（国际香精香料）华南研发中心 / 奇华顿广州应用中心',
        region: '华南',
        status: 'AVAILABLE',
        type: 'ENTERPRISE',
        specs: '应用研发中心/演示厨房（Demo Center）：全套微型工业肉机',
        capacity: '50kg/批次',
        equipment: '微型工业肉机,风味调试设备,感官评价室,质构分析仪',
        capabilities: '风味调试,多汁性改良,保质期优化,爆款逆向,快速打样',
        advantages: '全球顶级的原辅料巨头，在广州及周边设有强大的技术应用实验室。拥有全套微型工业肉机，专门帮客户调试肉制品的风味、多汁性和保质期。使用其辅料时，中试线常可提供极大优惠甚至免费。',
        cooperationModel: '辅料带货+产线开放：适合"调风味、做爆款逆向"需求。平台帮辅料商带货，换取对用户的产线开放权，用户使用指定辅料可享优惠甚至免费中试。',
        contactPerson: '应用技术部',
        contactPhone: '020-3819xxxx',
        contactEmail: 'apac-app@iff.com',
        pricePerDay: 4000,
        serviceFeePercent: 5,
        description: 'IFF（国际香精香料）与奇华顿（Givaudan）作为全球顶级原辅料巨头，在广州设有强大的技术应用研发中心。配备全套微型工业肉机，专门协助客户调试肉制品的风味、多汁性和保质期。使用其辅料可享中试优惠甚至免费。适合爆款逆向和快速风味打样。',
      },
      {
        name: '安琪酵母（东莞）应用技术中心',
        region: '华南',
        status: 'AVAILABLE',
        type: 'ENTERPRISE',
        specs: '应用技术中试车间：肉糜制品改良、减盐方案',
        capacity: '100kg/批次',
        equipment: '肉糜加工设备,质构测试仪,感官评价室,发酵监控设备',
        capabilities: '肉制品减盐,肉糜制品爽脆度改良,潮州牛肉丸,鱼糜制品,酵母抽提物应用',
        advantages: '安琪在珠三角布局极深。应用中心对肉制品减盐、肉糜制品（如潮州牛肉丸、鱼糜制品）的爽脆度改良有全套中试方案，车间对外开放度较高。',
        cooperationModel: '辅料带货+产线开放：适合肉糜制品（牛肉丸、鱼糜等）的爽脆度改良和减盐项目。使用安琪酵母抽提物等辅料可享中试优惠。',
        contactPerson: '应用技术部',
        contactPhone: '0769-2241xxxx',
        contactEmail: 'application@angel.com.cn',
        pricePerDay: 3000,
        serviceFeePercent: 5,
        description: '安琪酵母（东莞）应用技术中心是安琪在珠三角的重要布局。专注肉制品减盐、肉糜制品（潮州牛肉丸、鱼糜制品）爽脆度改良等中试方案，车间对外开放度高。特别适合广东特色肉糜制品的研发打样。',
      },
    ];

    for (const inst of prdInstitutions) {
      const existing = await prisma.$queryRaw<Array<{ id: number }>>`SELECT id FROM "PilotLine" WHERE name = ${inst.name}`;
      if (existing.length === 0) {
        await prisma.$executeRawUnsafe(
          `INSERT INTO "PilotLine" (name, region, status, specs, capacity, type, advantages, "cooperationModel", equipment, capabilities, "contactPerson", "contactPhone", "contactEmail", "pricePerDay", "serviceFeePercent", description) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)`,
          inst.name, inst.region, inst.status, inst.specs, inst.capacity, inst.type, inst.advantages, inst.cooperationModel, inst.equipment, inst.capabilities, inst.contactPerson, inst.contactPhone, inst.contactEmail, inst.pricePerDay, inst.serviceFeePercent, inst.description
        );
      }
    }
    logs.push(`PRD institutions seed OK (${prdInstitutions.length} institutions)`);

    // 12.6 Seed other regions pilot institutions (华东/华北/华中/西南)
    logs.push('Seeding other regions pilot institutions...');
    const otherRegionInstitutions = [
      // ===== 华东区域 =====
      {
        name: '江南大学 食品学院',
        region: '华东', status: 'AVAILABLE', type: 'UNIVERSITY',
        specs: '肉制品中试车间：乳化、灌装、蒸煮全流程',
        capacity: '200kg/批次',
        equipment: '乳化斩拌机,真空灌装机,烟熏炉,蒸煮槽,真空滚揉机',
        capabilities: '肉制品加工,食品配料,质构改良,清洁标签',
        advantages: '江南大学食品学院在全国食品学科排名第一，肉制品加工方向实力雄厚。拥有完整的肉制品中试车间，在乳化肠、低温肉制品、清洁标签等领域研究深入。',
        cooperationModel: 'CRO高客单价分成：适合高端肉制品研发、清洁标签、减盐等前沿课题的中试放大。',
        contactPerson: '学院科研办', contactPhone: '0510-8591xxxx', contactEmail: 'food@jiangnan.edu.cn',
        pricePerDay: 7000, serviceFeePercent: 10,
        description: '江南大学食品学院全国食品学科排名第一，肉制品加工方向实力雄厚。中试车间配备乳化、灌装、蒸煮全流程设备，适合高端肉制品研发中试。',
      },
      {
        name: '上海海洋大学 食品学院',
        region: '华东', status: 'AVAILABLE', type: 'UNIVERSITY',
        specs: '水产及肉类复合加工中试线',
        capacity: '150kg/批次',
        equipment: '复合加工中试线,低温慢煮设备,真空包装机,杀菌釜',
        capabilities: '水产肉制品复合加工,低温慢煮,即食产品,凝胶制品',
        advantages: '在水产与肉类复合加工领域有独特优势，低温慢煮技术和即食产品研发经验丰富，适合鱼糜肉糜复合制品的中试。',
        cooperationModel: 'CRO高客单价分成：适合水产肉糜复合制品、低温慢煮即食产品的研发中试。',
        contactPerson: '学院科研办', contactPhone: '021-6190xxxx', contactEmail: 'food@shou.edu.cn',
        pricePerDay: 5000, serviceFeePercent: 10,
        description: '上海海洋大学食品学院在水产与肉类复合加工领域有独特优势，低温慢煮技术和即食产品研发经验丰富。',
      },
      {
        name: '苏州预制菜产业园 公共中试平台',
        region: '华东', status: 'AVAILABLE', type: 'PARK',
        specs: '工业级预制菜中试线（含速冻、调理、包装）',
        capacity: '500kg/h',
        equipment: '液氮速冻隧道,调理肉制品中试线,自动包装线,金属检测仪',
        capabilities: '预制菜,调理肉制品,速冻肉类,轻资产研发',
        advantages: '长三角预制菜产业高地，公共服务平台配备工业级预制菜中试线，政府重点扶持，收费透明，适合长三角初创品牌打样试产。',
        cooperationModel: '标准场租抽佣：适合长三角预制菜初创品牌的打样试产需求，政府扶持收费透明。',
        contactPerson: '产业园运营办', contactPhone: '0512-6789xxxx', contactEmail: 'szypc@suzhou.gov.cn',
        pricePerDay: 3000, serviceFeePercent: 8,
        description: '苏州预制菜产业园是长三角预制菜产业高地，公共中试平台配备工业级预制菜中试线，政府重点扶持。',
      },
      {
        name: '嘉吉（中国）应用技术中心 上海',
        region: '华东', status: 'AVAILABLE', type: 'ENTERPRISE',
        specs: '应用研发中心：全套微型工业肉机+感官评价室',
        capacity: '50kg/批次',
        equipment: '微型工业肉机,质构分析仪,感官评价室,风味调试设备',
        capabilities: '风味调试,质构改良,淀粉应用,胶原蛋白应用,爆款逆向',
        advantages: '嘉吉作为全球最大的农业和食品企业之一，在上海设有应用技术中心，拥有全套微型工业肉机，提供肉类质构改良、淀粉和胶原蛋白应用方案。使用其辅料可享中试优惠。',
        cooperationModel: '辅料带货+产线开放：适合需要质构改良、淀粉/胶原蛋白应用的爆款逆向项目。使用嘉格辅料可享优惠或免费中试。',
        contactPerson: '应用技术部', contactPhone: '021-6090xxxx', contactEmail: 'apac-app@cargill.com',
        pricePerDay: 4000, serviceFeePercent: 5,
        description: '嘉吉（中国）应用技术中心在上海配备全套微型工业肉机和感官评价室，提供肉类质构改良、淀粉和胶原蛋白应用方案。',
      },
      // ===== 华北区域 =====
      {
        name: '中国农业大学 食品科学与营养工程学院',
        region: '华北', status: 'AVAILABLE', type: 'UNIVERSITY',
        specs: '肉品加工中试车间：灌装、蒸煮、烟熏全流程',
        capacity: '200kg/批次',
        equipment: '真空滚揉机,灌装机,烟熏炉,蒸煮槽,高压杀菌釜',
        capabilities: '肉品加工,营养强化,减盐减硝,传统肉制品现代化',
        advantages: '中国农业大学食品学院在肉品科学与营养工程领域全国领先，减盐减硝、营养强化等前沿研究方向成果丰硕。中试车间设备齐全，适合高端健康肉制品研发。',
        cooperationModel: 'CRO高客单价分成：适合减盐减硝、营养强化、健康肉制品等前沿研发课题的中试放大。',
        contactPerson: '学院科研办', contactPhone: '010-6273xxxx', contactEmail: 'food@cau.edu.cn',
        pricePerDay: 7000, serviceFeePercent: 10,
        description: '中国农业大学食品学院在肉品科学与营养工程领域全国领先，减盐减硝、营养强化等前沿研究方向成果丰硕。',
      },
      {
        name: '北京食品科学研究院',
        region: '华北', status: 'AVAILABLE', type: 'UNIVERSITY',
        specs: '中试基地：传统肉制品工业化、老字号升级',
        capacity: '150kg/批次',
        equipment: '酱卤中试线,烘烤设备,真空包装机,杀菌设备',
        capabilities: '传统肉制品工业化,老字号升级,北京烤鸭,酱卤制品',
        advantages: '北京食品科学研究院在传统肉制品工业化、老字号品牌升级方面有丰富经验，特别是北京烤鸭、酱卤制品的现代化改造。商业化对接流程灵活。',
        cooperationModel: 'CRO高客单价分成 + 技术转让：适合传统肉制品工业化升级、老字号品牌技术改造项目。',
        contactPerson: '技术转移中心', contactPhone: '010-8355xxxx', contactEmail: 'bifs@bifs.org.cn',
        pricePerDay: 5000, serviceFeePercent: 10,
        description: '北京食品科学研究院在传统肉制品工业化、老字号品牌升级方面经验丰富，特别是北京烤鸭、酱卤制品的现代化改造。',
      },
      {
        name: '河北高碑店农产品加工产业园 公共中试仓',
        region: '华北', status: 'AVAILABLE', type: 'PARK',
        specs: '全套柔性设备：原料处理→斩拌→灌装→熟制→速冻包装',
        capacity: '400kg/h',
        equipment: '原料处理设备,斩拌机,灌装机,熟制设备,速冻包装线',
        capabilities: '预制菜,柔性中试,中央厨房研发,全流程打样',
        advantages: '京津冀协同发展重点项目，公共中试仓提供从原料处理到速冻包装的全套柔性设备，专为京津冀地区中小品牌提供低成本中试打样服务。',
        cooperationModel: '标准场租抽佣：适合京津冀地区初创品牌的全流程打样需求，政府扶持收费透明。',
        contactPerson: '产业园运营办', contactPhone: '0312-281xxxx', contactEmail: 'gbdnyc@gaobeidian.gov.cn',
        pricePerDay: 2500, serviceFeePercent: 8,
        description: '河北高碑店农产品加工产业园是京津冀协同发展重点项目，公共中试仓提供全套柔性设备，专为京津冀地区中小品牌提供低成本中试服务。',
      },
      {
        name: '泰莱集团（Tate & Lyle）北京应用技术中心',
        region: '华北', status: 'AVAILABLE', type: 'ENTERPRISE',
        specs: '应用研发中心：减糖减脂方案、纤维强化肉制品',
        capacity: '50kg/批次',
        equipment: '微型工业肉机,质构测试仪,感官评价室,配方开发设备',
        capabilities: '减糖减脂,膳食纤维强化,清洁标签,质构改良,爆款逆向',
        advantages: '泰莱集团是全球领先的食品配料企业，在北京设有应用技术中心。在减糖减脂、膳食纤维强化肉制品方面有全套方案，使用其配料可享中试优惠。',
        cooperationModel: '辅料带货+产线开放：适合减糖减脂、健康肉制品的爆款逆向项目。使用泰莱配料可享优惠。',
        contactPerson: '应用技术部', contactPhone: '010-8518xxxx', contactEmail: 'apac-app@tateandlyle.com',
        pricePerDay: 3500, serviceFeePercent: 5,
        description: '泰莱集团（Tate & Lyle）在北京设有应用技术中心，在减糖减脂、膳食纤维强化肉制品方面有全套方案。',
      },
      // ===== 华中区域 =====
      {
        name: '华中农业大学 食品科技学院',
        region: '华中', status: 'AVAILABLE', type: 'UNIVERSITY',
        specs: '肉品加工中试车间：中式肉制品现代化',
        capacity: '200kg/批次',
        equipment: '真空滚揉机,灌装机,烟熏炉,蒸煮槽,酱卤中试线',
        capabilities: '中式肉制品现代化,酱卤工业化,肉品安全,传统工艺升级',
        advantages: '华中农业大学食品科技学院在肉品加工与安全领域实力雄厚，尤其在中式肉制品现代化、酱卤工业化方面有丰富成果。与华中地区肉企有深度合作。',
        cooperationModel: 'CRO高客单价分成：适合中式肉制品现代化升级、传统工艺工业化改造的中试需求。',
        contactPerson: '学院科研办', contactPhone: '027-8728xxxx', contactEmail: 'food@hzau.edu.cn',
        pricePerDay: 5000, serviceFeePercent: 10,
        description: '华中农业大学食品科技学院在肉品加工与安全领域实力雄厚，尤其在中式肉制品现代化、酱卤工业化方面有丰富成果。',
      },
      {
        name: '湖南岳阳预制菜产业园 公共中试平台',
        region: '华中', status: 'AVAILABLE', type: 'PARK',
        specs: '工业级调理肉制品中试线',
        capacity: '400kg/h',
        equipment: '调理肉制品中试线,速冻设备,真空包装机,金属检测仪',
        capabilities: '预制菜,调理肉制品,湘味肉制品,轻资产研发',
        advantages: '岳阳作为湖南预制菜产业核心区，公共服务平台配备工业级调理肉制品中试线。湘味肉制品特色鲜明，政府大力扶持，适合华中地区初创品牌。',
        cooperationModel: '标准场租抽佣：适合华中地区预制菜初创品牌、湘味肉制品的打样试产需求。',
        contactPerson: '产业园管委会', contactPhone: '0730-821xxxx', contactEmail: 'yyypc@yueyang.gov.cn',
        pricePerDay: 2500, serviceFeePercent: 8,
        description: '岳阳预制菜产业园是湖南预制菜产业核心区，公共服务平台配备工业级调理肉制品中试线，湘味肉制品特色鲜明。',
      },
      {
        name: '双汇集团 研发中心（河南漯河）',
        region: '华中', status: 'AVAILABLE', type: 'ENTERPRISE',
        specs: '企业级中试线：高温火腿肠、低温肉制品全流程',
        capacity: '500kg/h',
        equipment: '高速灌装线,高温杀菌釜,低温蒸煮线,真空包装机,斩拌机',
        capabilities: '高温肉制品,低温肉制品,火腿肠工艺,规模化生产验证',
        advantages: '双汇集团是中国最大的肉类加工企业，研发中心配备企业级中试线，可进行高温火腿肠、低温肉制品的全流程中试验证。适合需要规模化验证的项目。',
        cooperationModel: '辅料带货+产线开放：适合需要规模化生产验证的高温/低温肉制品项目。合作模式灵活，可技术合作。',
        contactPerson: '研发中心合作办', contactPhone: '0395-262xxxx', contactEmail: 'rnd@shuanghui.net',
        pricePerDay: 5000, serviceFeePercent: 5,
        description: '双汇集团研发中心配备企业级中试线，可进行高温火腿肠、低温肉制品的全流程中试验证，适合需要规模化验证的项目。',
      },
      // ===== 西南区域 =====
      {
        name: '四川大学 轻工科学与工程学院',
        region: '西南', status: 'AVAILABLE', type: 'UNIVERSITY',
        specs: '肉制品中试车间：川味肉制品现代化',
        capacity: '150kg/批次',
        equipment: '酱卤中试线,烘烤设备,真空包装机,杀菌设备,乳化设备',
        capabilities: '川味肉制品,酱卤工业化,肉干制品,休闲肉制品',
        advantages: '四川大学在川味肉制品现代化、肉干制品工艺领域有深厚积累。对川味香肠、腊肉、肉干等传统产品的工业化升级有丰富经验。',
        cooperationModel: 'CRO高客单价分成：适合川味肉制品现代化、传统肉干制品工艺升级的中试需求。',
        contactPerson: '学院科研办', contactPhone: '028-8546xxxx', contactEmail: 'food@scu.edu.cn',
        pricePerDay: 4500, serviceFeePercent: 10,
        description: '四川大学在川味肉制品现代化、肉干制品工艺领域有深厚积累，对川味香肠、腊肉、肉干等传统产品的工业化升级有丰富经验。',
      },
      {
        name: '成都食品产业园 公共中试平台',
        region: '西南', status: 'AVAILABLE', type: 'PARK',
        specs: '工业级川味肉制品中试线',
        capacity: '400kg/h',
        equipment: '酱卤中试线,灌装线,烘烤设备,真空包装机,速冻设备',
        capabilities: '川味肉制品,酱卤制品,休闲肉制品,预制菜,轻资产研发',
        advantages: '成都食品产业园是西南地区最大的食品加工集聚区，公共中试平台配备工业级川味肉制品中试线。川味特色鲜明，政府大力扶持。',
        cooperationModel: '标准场租抽佣：适合西南地区川味肉制品、预制菜初创品牌的打样试产需求。',
        contactPerson: '产业园运营办', contactPhone: '028-8765xxxx', contactEmail: 'cdsp@chengdu.gov.cn',
        pricePerDay: 2500, serviceFeePercent: 8,
        description: '成都食品产业园是西南地区最大的食品加工集聚区，公共中试平台配备工业级川味肉制品中试线，川味特色鲜明。',
      },
      {
        name: '新希望六和 食品研发中心（成都）',
        region: '西南', status: 'AVAILABLE', type: 'ENTERPRISE',
        specs: '企业级中试线：调理肉制品、预制菜全流程',
        capacity: '300kg/h',
        equipment: '调理肉制品中试线,灌装机,速冻设备,真空包装机,杀菌设备',
        capabilities: '调理肉制品,预制菜,低温肉制品,规模化验证,风味调优',
        advantages: '新希望六和是中国农牧食品龙头企业，在成都设有食品研发中心，配备企业级中试线。在调理肉制品、预制菜领域经验丰富，可对接产业链资源。',
        cooperationModel: '辅料带货+产线开放：适合调理肉制品、预制菜的规模化中试验证。可对接新希望产业链资源。',
        contactPerson: '研发中心合作办', contactPhone: '028-8532xxxx', contactEmail: 'rnd@newhope.cn',
        pricePerDay: 4500, serviceFeePercent: 5,
        description: '新希望六和食品研发中心在成都配备企业级中试线，在调理肉制品、预制菜领域经验丰富，可对接产业链资源。',
      },
    ];

    for (const inst of otherRegionInstitutions) {
      const existing = await prisma.$queryRaw<Array<{ id: number }>>`SELECT id FROM "PilotLine" WHERE name = ${inst.name}`;
      if (existing.length === 0) {
        await prisma.$executeRawUnsafe(
          `INSERT INTO "PilotLine" (name, region, status, specs, capacity, type, advantages, "cooperationModel", equipment, capabilities, "contactPerson", "contactPhone", "contactEmail", "pricePerDay", "serviceFeePercent", description) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)`,
          inst.name, inst.region, inst.status, inst.specs, inst.capacity, inst.type, inst.advantages, inst.cooperationModel, inst.equipment, inst.capabilities, inst.contactPerson, inst.contactPhone, inst.contactEmail, inst.pricePerDay, inst.serviceFeePercent, inst.description
        );
      }
    }
    logs.push(`Other regions institutions seed OK (${otherRegionInstitutions.length} institutions)`);

    // 13. Create Bill table
    logs.push('Creating Bill table...');
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS "Bill" (
        id SERIAL PRIMARY KEY,
        "bookingId" INTEGER NOT NULL UNIQUE,
        "lineId" INTEGER NOT NULL,
        "customerName" TEXT NOT NULL,
        "customerPhone" TEXT NOT NULL,
        "customerEmail" TEXT NOT NULL,
        "company" TEXT NOT NULL,
        "amount" DOUBLE PRECISION NOT NULL DEFAULT 0,
        "serviceFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
        "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
        "status" TEXT NOT NULL DEFAULT 'PENDING',
        "invoiceRequested" BOOLEAN NOT NULL DEFAULT false,
        "invoiceInfo" TEXT NOT NULL DEFAULT '',
        "paidAt" TIMESTAMP(3),
        "note" TEXT NOT NULL DEFAULT '',
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3)
      )
    `);
    // Add foreign key constraints
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "Bill" ADD CONSTRAINT "Bill_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"(id) ON DELETE RESTRICT ON UPDATE CASCADE`);
    } catch (e) {}
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "Bill" ADD CONSTRAINT "Bill_lineId_fkey" FOREIGN KEY ("lineId") REFERENCES "PilotLine"(id) ON DELETE RESTRICT ON UPDATE CASCADE`);
    } catch (e) {}
    logs.push('Bill table OK');

    // 14. Add Bill relation to Booking
    logs.push('Adding Bill relation to Booking...');
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "billId" INTEGER`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Booking" ADD CONSTRAINT "Booking_billId_fkey" FOREIGN KEY ("billId") REFERENCES "Bill"(id) ON DELETE SET NULL ON UPDATE CASCADE`);
      logs.push('Booking.billId OK');
    } catch (e) {
      logs.push('Booking.billId already exists or skip');
    }

    // 15. Create Media table
    logs.push('Creating Media table...');
    try {
      await prisma.$executeRawUnsafe(`
        CREATE TABLE IF NOT EXISTS "Media" (
          id SERIAL PRIMARY KEY,
          filename TEXT NOT NULL,
          "originalName" TEXT NOT NULL,
          url TEXT NOT NULL,
          "thumbnailUrl" TEXT,
          "mimeType" TEXT NOT NULL,
          size INTEGER NOT NULL,
          width INTEGER,
          height INTEGER,
          duration INTEGER,
          type TEXT NOT NULL DEFAULT 'IMAGE',
          folder TEXT NOT NULL DEFAULT 'default',
          alt TEXT NOT NULL DEFAULT '',
          caption TEXT NOT NULL DEFAULT '',
          "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
          "updatedAt" TIMESTAMP(3)
        )
      `);
      logs.push('Media table OK');
    } catch (e: any) {
      logs.push('Media table already exists or skip');
    }

    // 16. Add new columns to Product
    logs.push('Adding new columns to Product...');
    try {
      await prisma.$executeRawUnsafe(`ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "content" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "tags" TEXT NOT NULL DEFAULT ''`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0`);
      await prisma.$executeRawUnsafe(`ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3)`);
      await prisma.$executeRawUnsafe(`UPDATE "Product" SET "updatedAt" = "createdAt" WHERE "updatedAt" IS NULL`);
      logs.push('Product new columns OK');
    } catch (e) {
      logs.push('Product columns already exist or skip');
    }

    // 17. Seed homepage carousel settings
    logs.push('Seeding homepage settings...');
    const homepageSettings = [
      { key: 'homepage_carousel', value: JSON.stringify([
        { tag: '平台介绍', title: '肉制品研发与智能中试平台', desc: '从深度技术长文到中试产线预约，从工艺问答到同行交流——全链路服务肉制品研发，赋能每一位肉品工艺工程师', bg: 'carousel-bg-4', btn: '了解平台全部功能', link: '/tool/pilot-map' },
        { tag: '商超爆款逆向工程', title: '山姆某款爆汁脆皮肠', desc: '从"货架到车间"的工业化落地工艺参数拆解，涵盖原料配比、灌装工艺、蒸煮曲线全流程', bg: 'carousel-bg-1', btn: '点击查看工艺说明书及基础配方', link: '/product/1' },
        { tag: '中试产线动态', title: '华南区液氮速冻隧道产线开放预约', desc: '-196液氮速冻隧道，适用于预制菜速冻工艺验证，本周新增3个档期，先到先得', bg: 'carousel-bg-3', btn: '立即查看档期并预约', link: '/booking' },
      ]) },
      { key: 'homepage_industry', value: JSON.stringify([
        { icon: '🔬', tag: '辅料应用', tagBg: '#FEF3C7', tagColor: '#92400E', title: '复配磷酸盐在低温火腿中的保水优化方案', desc: '对比三聚磷酸钠、六偏磷酸钠及其复配方案在低温火腿中的保水效果，涵盖pH调节、蛋白质溶解度、质构分析等关键指标。', link: '/search?q=复配磷酸盐' },
        { icon: '⚙️', tag: '机械选型', tagBg: '#DBEAFE', tagColor: '#1E40AF', title: '汇川/西门子 PLC 控制系统在现代化高速斩拌机中的温度精准控制实践', desc: '对比汇川H3U系列与西门子S7-1200在高速斩拌机（6000rpm）刀盘温度闭环控制中的响应精度与稳定性表现，涵盖PID参数整定方法。', link: '/search?q=PLC斩拌机' },
        { icon: '📦', tag: '包装创新', tagBg: '#D1FAE5', tagColor: '#065F46', title: '莫迪维克（Multivac）高阻隔气调包装对低温冷鲜肉货架期延长突破', desc: '基于Multivac R245封口机平台，测试70%O₂+30%CO₂气调配比下，不同阻隔膜对低温冷鲜猪肉货架期的影响。7层共挤膜可将货架期从12天延长至21天。', link: '/search?q=气调包装' },
      ]) },
      { key: 'homepage_footer', value: JSON.stringify({
        title: '📱 加入肉品工程师日常技术互助群（微信私域沉淀）',
        subtitle: '按品类分群，扫码加入对应技术交流群',
        groups: [
          { icon: '🍖', name: '中式酱卤交流群', qrcode: '' },
          { icon: '🥓', name: '西式低温技术群', qrcode: '' },
          { icon: '🍱', name: '肉品预制菜研发群', qrcode: '' },
        ],
      }) },
      { key: 'homepage_pilot', value: JSON.stringify({
        slogan: '💡 核心创新板块',
        title: '柔性中试中心 —— 在线预约你的肉品工业实验室',
        subtitle: '无需买设备，盘活全行业闲置产能，打造肉类行业的"药明康德（CRO）"',
        mapIntro: '覆盖全国主要区域的肉类中试资源网络，每区域均面向三类客户服务：高校科研院所（CRO研发）、产业园公共平台（轻资产试错）、辅料企业演示中心（风味调优与爆款逆向）。',
        cooperationModels: [
          { icon: '🎓', title: '找专家、做大改动', desc: '引流到高校科研院所，走CRO高客单价分成模式', bg: 'linear-gradient(135deg, #DBEAFE 0%, #EFF6FF 100%)', borderColor: '#BFDBFE', color: '#1E3A8A' },
          { icon: '🏭', title: '初创品牌、预制菜试错', desc: '推荐到公共中试仓，走标准场租抽佣，政府扶持收费透明', bg: 'linear-gradient(135deg, #D1FAE5 0%, #ECFDF5 100%)', borderColor: '#A7F3D0', color: '#065F46' },
          { icon: '🧪', title: '调风味、做爆款逆向', desc: '撮合到辅料巨头演示中心，辅料带货换取产线开放', bg: 'linear-gradient(135deg, #FEF3C7 0%, #FFFBEB 100%)', borderColor: '#FDE68A', color: '#92400E' },
        ],
      }) },
      { key: 'homepage_sections', value: JSON.stringify({
        heroBadge: '🥩 肉制品研发与智能中试平台',
        heroSlogan: '赋能每一位肉品工艺工程师',
        heroSub: '从深度技术长文到中试产线预约，从疑难问答到同行交流，全链路服务肉制品研发',
        heroCtaPrimary: '💬 进入工艺问答讨论',
        heroCtaSecondary: '🏭 预约中试线',
        reverseIcon: '📌', reverseTitle: '货架直通车间', reverseBadge: '商超爆款逆向研发',
        reverseIntro: '追踪山姆、盒马等零售终端销量走势，逆向拆解工业化量产工艺',
        scienceIcon: '🔬', scienceTitle: '硬核肉品科学', scienceBadge: '工业配方重构与故障排查矩阵',
        scienceIntro: '深入肉类生物化学底层，解决清洁标签、减盐减硝等现代改性需求',
        communityBadge: '💬 工艺工程师讨论社区',
        communityTitle: '有问题随时问，有经验随时分享',
        communitySub: '出水、散肉、色泽不均、保质期不达标……遇到工艺难题，发帖求助同行专家。已有技术内容沉淀，持续更新中。',
        industryIcon: '⚙️', industryTitle: '工业4.0', industryBadge: '设备选型与原辅料应用指南',
        industryIntro: '拒绝硬广告，只看辅料与设备在实际生产中的"应用案例（Case Study）"',
      }) },
      { key: 'homepage_reverse', value: JSON.stringify([
        { title: '山姆某款爆汁脆皮肠', category: '低温调理肉', difficulty: '灌装致密性、蒸煮曲线控制、脆皮成型温度窗口窄', link: '/product/1', icon: '🥓', tags: '山姆,脆皮肠,逆向' },
        { title: '盒马气调保鲜预制菜系列', category: '气调预制菜', difficulty: '气调配比优化、货架期延长、微生物控制', link: '/product/2', icon: '🍳', tags: '盒马,气调,预制菜' },
        { title: '某品牌低盐健康香肠', category: '休闲及其他', difficulty: '减盐后的质构保持、保水性下降、风味平衡', link: '/product/3', icon: '🌶️', tags: '低盐,健康,香肠' },
      ]) },
    ];
    for (const s of homepageSettings) {
      await prisma.$executeRawUnsafe(
        `INSERT INTO "Setting" (key, value) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING`,
        s.key, s.value
      );
    }
    logs.push('Homepage settings OK');

    // 18. Seed 100 Q&A discussion posts
    logs.push('Seeding 100 Q&A discussion posts...');
    try {
      const qaCategory = await prisma.category.findUnique({ where: { slug: 'community-qa' } });
      if (qaCategory) {
        const existingQA = await prisma.$queryRaw<Array<{ id: number }>>`SELECT id FROM "Post" WHERE slug LIKE 'qa-%' LIMIT 1`;
        if (existingQA.length === 0) {
          const qaItems = getQAItems();
          let seeded = 0;
          for (const item of qaItems) {
            try {
              const daysAgo = Math.floor(Math.random() * 30);
              const createdDate = new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000);
              await prisma.post.create({
                data: {
                  title: item.title,
                  slug: item.slug,
                  excerpt: item.excerpt,
                  content: item.content,
                  author: item.author,
                  tags: item.tags,
                  status: 'PUBLISHED',
                  categoryId: qaCategory.id,
                  createdAt: createdDate,
                  updatedAt: createdDate,
                },
              });
              seeded++;
            } catch (e) { /* skip individual errors */ }
          }
          logs.push(`Seeded ${seeded} Q&A posts (out of ${qaItems.length})`);
        } else {
          logs.push('Q&A posts already seeded');
        }
      } else {
        logs.push('community-qa category not found, skip Q&A seeding');
      }
    } catch (e) {
      logs.push(`Q&A seeding error: ${e instanceof Error ? e.message : String(e)}`);
    }

    // 19. One-time migration: add platform highlight slide to existing carousels that don't have it
    // (New installations get it directly from the seed data in Step 17)
    logs.push('Checking carousel for platform slide...');
    try {
      const existingCarousel = await prisma.setting.findUnique({ where: { key: 'homepage_carousel' } });
      if (existingCarousel) {
        const carouselData = JSON.parse(existingCarousel.value);
        const hasPlatformSlide = carouselData.some((item: any) => item.tag === '平台介绍');
        if (!hasPlatformSlide && Array.isArray(carouselData)) {
          carouselData.unshift({
            tag: '平台介绍',
            title: '肉制品研发与智能中试平台',
            desc: '从深度技术长文到中试产线预约，从工艺问答到同行交流——全链路服务肉制品研发，赋能每一位肉品工艺工程师',
            bg: 'carousel-bg-4',
            btn: '了解平台全部功能',
            link: '/tool/pilot-map',
          });
          await prisma.$executeRawUnsafe(`UPDATE "Setting" SET value = $1 WHERE key = 'homepage_carousel'`, JSON.stringify(carouselData));
          logs.push('Carousel updated with platform slide (one-time migration)');
        } else {
          logs.push('Carousel already has platform slide (or not an array, skip)');
        }
      }
    } catch (e) {
      logs.push(`Carousel update skip: ${e instanceof Error ? e.message : String(e)}`);
    }

    logs.push('=== Setup completed successfully ===');
    return NextResponse.json({ success: true, logs });
  } catch (error) {
    logs.push(`ERROR: ${error instanceof Error ? error.message : String(error)}`);
    return NextResponse.json({ success: false, logs, error: error instanceof Error ? error.message : String(error) }, { status: 500 });
  }
}
